# Generated by Django 3.1.3 on 2020-11-14 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("matching", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mentee",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("MenteeId", models.IntegerField()),
                ("FName", models.TextField()),
                ("LName", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Mentor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("MentorId", models.IntegerField()),
                ("FName", models.TextField()),
                ("LName", models.TextField()),
                ("Industry", models.IntegerField()),
                (
                    "Pairing",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="matching.mentee",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="mentee",
            name="Pairing",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="matching.mentor",
            ),
        ),
    ]
