# Generated by Django 3.1.3 on 2020-11-14 22:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("matching", "0003_auto_20201114_2214"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentee",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mentee",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="mentee",
            name="other_attributes",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="mentee",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="mentor",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mentor",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="mentor",
            name="other_attributes",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="mentor",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
