# Generated by Django 3.1.3 on 2020-11-15 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0005_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentee',
            name='cohort',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='matching.cohort'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='cohort',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='matching.cohort'),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='other_attributes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='other_attributes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
