# Generated by Django 3.1.3 on 2020-12-29 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0006_auto_20201115_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentee_column_name', models.CharField(max_length=200)),
                ('mentor_column_name', models.CharField(max_length=200)),
                ('weight', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'MatchConfig',
            },
        ),
    ]
